topics:
-
  name: remote
  topic: remote/cmd_vel
  timeout: 0.5
  priority: 10
-
  name: navigation
  topic: navigation/cmd_vel
  timeout: 0.5
  priority: 5
-
  name: zero
  topic: zero/cmd_vel
  timeout: 0.5
  priority: 1
locks:
-
  name: e_stop
  topic: e_stop
  timeout: 0.0
  priority: 255
