# Local planner
DWAPlannerROS:
  # Robot configuration parameters DWA
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.0

  max_vel_trans: 0.5
  min_vel_trans: 0.1

  max_vel_x: 0.5
  min_vel_x: -0.5

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_theta: 0.5
  min_vel_theta: -0.5

  # Robot configuration parameters Base local
  min_in_place_vel_theta: 0.01
  escape_vel: -0.2

  # Goal Tolerance Parameters
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.5

  # Forward Simulation Parameters
  sim_time: 1.2
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  # ! Forward Simulation Parameters Base local
  angular_sim_granularity: 0.17

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
  track_unknown_space: false
  publish_cost_grid: true
  prune_plan: false
