scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: 0.175
    max_y: 0.135
    max_z: 0.5
    min_x: -0.175
    min_y: -0.135
    min_z: -0.5
    invert: false # activate to remove all points outside of the box
